app = "gamblecodez"

[build]
  image = "node:18"

[env]
  PORT = "3000"
  ADMIN_USER = "Admin"
  ADMIN_PASS = "Pink2222"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443